config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  root to: "dashboard#index"

  resources :dashboard, only: [ :index ]
  resources :user, only: [ :show, :new, :create, :destroy ]
  resources :post, only: [ :show, :new, :create ] do
    resources :comments, only: [ :create ]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :body, length: { maximum: 100 }
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  validates :username, presence: true, uniqueness: true
  validates :email_address, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  allow_unauthenticated_access

  def create
    if authenticated?
      @user = User.find_by_username(Current.user.username)
    end
    @post = Post.find(params[:post_id])
    # @comment = @post.comments.build(content: params[:content], user: @user)
    @comment = @post.comments.build(comment_params)
    @comment.user = @user

    if @comment.save
      redirect_to @post
    else
      render "post/show", status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end


    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id])
    end


    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end


    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  allow_unauthenticated_access only: [ :index ]

  def index
    @users_posts = []

    User.all.each do |user|
      @users_posts.push(user.posts.all)
    end
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  allow_unauthenticated_access only: [ :show ]

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
  end

  def new
    @post = Post.new(params[:post])
  end

  def create
    @user = Current.user
    @post = @user.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to dashboard_index_path, notice: "Welcome #{user.username}!"
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  allow_unauthenticated_access

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new(params[:user])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path
    else
      render "new", status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      redirect_to root_path
    else
      redirect_to @user
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email_address, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/new.html.erb
<h1></h1>

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>

<% if authenticated? %>
  <p>Logged in as : <%= Current.user.email_address %></p>
  <%= link_to "Sign out", session_path, data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %>
<% end %>


<hr>

<div class="posts-group">
  <% @users_posts.each do |user| %>
    <% user.each do |post| %>
      <div>
        <h3><%= post.title %></h3>
        <p><%= post.body %></p>
        <%= link_to "Check the post", post %>
      </div>
    <% end %>
  <% end %>
</div>

<hr>

<%= link_to "Make new post", new_post_path %>
<br>
<%= link_to "Login", new_session_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Micro Reddit" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/post/_postform.html.erb
<%= form_with model: @post, url: post_index_path, local: true do |form| %>

  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit "Post" %>
  </div>
<% end %>

app/views/post/new.html.erb
<h1><%= link_to "<", dashboard_index_path %></h1>

<h1>New Post</h1>

<%= render "postform" %>

app/views/post/show.html.erb
<h1><%= link_to "<", dashboard_index_path %></h1>

<h1><%= @post.title %></h1>
<p><%= @post.body %></p>

<!--<h1>Post = <%#= @post.body %></h1>-->
<!--<h1>User = <%#= @user.username %></h1>-->

<%#= link_to "Created by " + @user.username, @user %>

<hr>

<h1>Comment</h1>

<%= form_with model: [@post, @post.comments.build], local: true do |form| %>
  <div>
    <%= form.label :content, "Enter your comment" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit "Create Comment" %>
  </div>
<% end %>

app/views/user/_form.html.erb
<%= form_with model: @user, url: user_index_path, local: true do |form| %>
  <div class="form-group">

    <div>
      <% if @user.errors.any? %>
        <% @user.errors.full_messages.each do |message| %>
          <p><%= message %></p>
        <% end %>
      <% end %>
    </div>

    <div>
      <%= form.label :username, "Username" %>
      <%= form.text_field :username %>
    </div>

    <div>
      <%= form.label :email_address, "Email" %>
      <%= form.text_field :email_address %>
    </div>

    <div>
      <%= form.label :password, "Password" %>
      <%= form.text_field :password %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/user/new.html.erb
<h1>New Author</h1>

<%= render "form" %>

<br>

<%= link_to "Back to login", new_session_path %>

<br>

<%= link_to "Back to Index", dashboard_index_path %>

app/views/user/show.html.erb
<h1><%= link_to "<", :back %></h1>
<h1>Profile</h1>

<h3>Username : <%= @user.username %></h3>
<h3>Email : <%= @user.email_address %></h3>


<%= link_to "Delete User", @user, data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"
} %>

<%= link_to "Back to Dashboard", dashboard_index_path %>